### ISSUE TITLE
DLNA devices unreachable

### ISSUE THREAD

**Issue by mrashisha** [linuxserver/docker-serviio#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I am relatively new to Docker and I am guessing this may just be a trivial question for you guys. I am using the command outlined  in the README to create the container and it seems to start up fine. However, I wasn't able to get to the console when I try http://localhost:23423/console and it does not show up any of my DLNA devices

I assumed it had something to do with the fact that docker is running through a VM since its a Mac, so I ended up creating a docker-compose.yml to declare explicit port mappings and removed the net=host setting
```
version: '2'
services:
  serviio:
    container_name: serviio
    image: lsiocommunity/serviio
    restart: unless-stopped
    ports:
      - 1900:1900/udp
      - 8895:8895/tcp
      - 23423:23423/tcp
      - 23424:23424/tcp
      - 23523:23523/tcp
      - 23524:23524/tcp
    environment:
      - PUID=1000
      - PGID=2000
    hostname: ServiioServer
    volumes:
      - ~/serviio/config:/config
      - ~/serviio/transcode:/transcode
      - ~/media/tvshows:/media/tvshows
      - ~/media/movies:/media/movies
```
There are no symlinks in the volume mounts.

I was then able to access the console and mediabrowser on my laptop using http://localhost:23423/console and everything is fine on my localhost, however my DLNA devices which are connected to the same wifi, are still unable to identify Serviio

Previously I had installed Serviio directly (i.e. not through Docker) on my Mac  and the same DLNA devices were able to recognize that its running

What do I need to change to get this to work with Docker?
